### ISSUE TITLE
Tour - banner carousel is displayed darker than it should 

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#166] opened 2023-06-14 12:48 UTC
https://main--realmadrid--hlxsites.hlx.page/sites/tour-bernabeu/colegios/guiada

<img width="1520" alt="Screenshot 2023-06-14 at 14 47 06" src="https://github.com/hlxsites/realmadrid/assets/43381734/5b025e78-2c29-4dcd-9f90-a4e7f61ddcfd">

**Comment by vdua** [comment] 2023-06-20 04:07
@chicharr The issue is with the design of the block and its usage. The block requires only 1 image while two images are provided in the content (that was the original design, which was changed later in #145). I have updated the fragment for now to resolve this issue.

<img width="855" alt="image" src="https://github.com/hlxsites/realmadrid/assets/2097597/008765c9-0805-44a9-ae3e-6d2bc551e99d">

**Comment by msagolj** [comment] 2023-06-21 15:13
Closing ticket as there doesnt really seem to be a need for a smaller image.

**Closed by msagolj** 2023-06-21 15:13 UTC
Labels: bug
